List<String> governorates = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Dakahlia",
  "Red Sea",
  "Beheira",
  "Fayoum",
  "Gharbia",
  "Ismailia",
  "Menofia",
  "Minya",
  "Qaliubiya",
  "New Valley",
  "Suez",
  "Aswan",
  "Assiut",
  "Beni Suef",
  "Port Said",
  "Damietta",
  "Sharkia",
  "South Sinai",
  "Kafr El Sheikh",
  "Matrouh",
  "Luxor",
  "Qena",
  "North Sinai",
  "Sohag",
];

const Map<String, List<String>> cities = {
  'Cairo': [
    'Nasr City',
    'Heliopolis',
    'Maadi',
    'Mokattam',
    'New Cairo',
    'Shubra',
    'Downtown',
    'El Marg',
    'El Basatin',
    'El Sayeda Zeinab',
    'El Khalifa',
    'El Manyal',
    'El Zawya El Hamra',
    'Ain Shams',
    'El Salam City',
    'Badr City',
    'El Shorouk City',
    '15th of May City'
  ],
  'Giza': [
    'Dokki',
    'Agouza',
    'Mohandessin',
    'Haram',
    'Faisal',
    '6th of October City',
    'Sheikh Zayed City',
    'Imbaba',
    'Bulaq Dakrour',
    'Warraq',
    'Al-Badrashin',
    'Awsim',
    'Atfih',
    'El Saf',
    'Kerdasa',
    'Abu Nomros'
  ],
  'Alexandria': [
    'Raml Station',
    'Sidi Gaber',
    'Sidi Bishr',
    'Miami',
    'Smouha',
    'Sporting',
    'Cleopatra',
    'Mansheya',
    'Anfoushi',
    'Bahary',
    'Agami',
    'Borg El Arab',
    'Amreya'
  ],
  'Dakahlia': [
    'Mansoura',
    'Talkha',
    'Mit Ghamr',
    'Aga',
    'El Sinbellawein',
    'Dikirnis',
    'Sherbin',
    'Belqas',
    'Meniet El Nasr',
    'Gamasa',
    'Temay Alamded',
    'Mahalet Damana',
    'Bani Ebeid',
    'Nabaroh'
  ],
  'Red Sea': [
    'Hurghada',
    'Safaga',
    'Quseir',
    'Marsa Alam',
    'Ras Ghareb',
    'Shalateen',
    'Halayeb'
  ],
  'Beheira': [
    'Damanhour',
    'Kafr El Dawwar',
    'Rashid',
    'Edko',
    'Itay El Baroud',
    'Kom Hamada',
    'Hosh Essa',
    'Delengat',
    'Abu Hummus',
    'Shubrakhit',
    'Mahmoudiya',
    'Rahmaniya',
    'Badr',
    'Nubariya'
  ],
  'Fayoum': ['Fayoum', 'Tamiya', 'Sinnuris', 'Itsa', 'Etsa', 'Yusuf El Sediq'],
  'Gharbia': [
    'Tanta',
    'El Mahalla El Kubra',
    'Kafr El Zayat',
    'Zifta',
    'Samannoud',
    'El Santa',
    'Qutour',
    'Basyoun'
  ],
  'Ismailia': [
    'Ismailia',
    'Fayed',
    'Qantara West',
    'Qantara East',
    'Tell El Kebir',
    'Abu Suwir',
    'Kasasien'
  ],
  'Menofia': [
    'Shibin El Kom',
    'Quesna',
    'Ashmoun',
    'Menouf',
    'Sers El Lyan',
    'Tala',
    'El Bagour',
    'Sadat City',
    'Berket El Sabaa'
  ],
  'Minya': [
    'Minya',
    'Samalut',
    'Maghagha',
    'Beni Mazar',
    'Matay',
    'Abu Qurqas',
    'Malawi',
    'Deir Mawas'
  ],
  'Qaliubiya': [
    'Banha',
    'Qalyub',
    'Shubra El Kheima',
    'Khanka',
    'Khosous',
    'Qanater',
    'Tokh',
    'Shebin El Qanater',
    'Kafr Shukr'
  ],
  'New Valley': ['Kharga', 'Dakhla', 'Farafra', 'Baris', 'Balat'],
  'Suez': ['Suez', 'Ain Sokhna', 'Ataqah'],
  'Aswan': ['Aswan', 'Edfu', 'Kom Ombo', 'Daraw', 'Abu Simbel'],
  'Assiut': [
    'Assiut',
    'Abnub',
    'Abu Tig',
    'Dairut',
    'Manfalut',
    'El Badari',
    'Saqolta',
    'El Qusiya'
  ],
  'Beni Suef': [
    'Beni Suef',
    'El Wasta',
    'Nasser',
    'Ehnasia',
    'Beba',
    'Samasta',
    'Al Fashn'
  ],
  'Port Said': ['Port Fouad', 'Port Said'],
  'Damietta': [
    'Damietta',
    'New Damietta',
    'Kafr Saad',
    'Zarqa',
    'Faraskour',
    'Kafr El Battikh',
    'Ras El Bar'
  ],
  'Sharkia': [
    'Zagazig',
    '10th of Ramadan City',
    'Belbeis',
    'Abu Hammad',
    'Abu Kebir',
    'Hehia',
    'Kafr Saqr',
    'Awlad Saqr',
    'Faqous',
    'El Ibrahimeya',
    'Diyarb Negm',
    'El Qurein',
    'Mashtool El Souk',
    'San El Hagar',
    'Husseiniya'
  ],
  'South Sinai': [
    'Sharm El Sheikh',
    'Dahab',
    'El Tor',
    'Ras Sudr',
    'Nuweiba',
    'Taba',
    'Saint Catherine'
  ],
  'Kafr El Sheikh': [
    'Kafr El Sheikh',
    'Desouk',
    'Fouh',
    'Metoubes',
    'Baltim',
    'El Hamoul',
    'Sidi Salem',
    'Qallin',
    'Beila',
    'Riadh'
  ],
  'Matrouh': [
    'Marsa Matrouh',
    'Siwa',
    'El Alamein',
    'El Dabaa',
    'Sidi Barrani',
    'El Salloum',
    'Hamam',
    'Noubaria'
  ],
  'Luxor': ['Luxor', 'Armant', 'Esna', 'El Tod', 'New Tiba'],
  'Qena': [
    'Qena',
    'Deshna',
    'Qift',
    'Qus',
    'Naqada',
    'Abu Tesht',
    'Farshut',
    'Naga Hammadi'
  ],
  'North Sinai': [
    'Arish',
    'Sheikh Zuweid',
    'Rafah',
    'Bir al-Abd',
    'Nakhl',
    'Hasna'
  ],
  'Sohag': [
    'Sohag',
    'Tahta',
    'Girga',
    'Akhmim',
    'El Balyana',
    'Tama',
    'Dar El Salam',
    'Sakulta',
    'Maragha',
    'Monsha\'a'
  ],
};

const List<String> specialties = [
  "Cardiology",
  "Dermatology",
  "Dentistry",
  "General Surgery",
  "Neurology",
  "Oncology",
  "Orthopedics",
  "Pediatrics",
  "Psychiatry",
  "Urology",
  "ENT",
  "Internal Medicine",
  "Ophthalmology",
  "Gynecology",
  "Nutrition",
  "Physiotherapy",
];
